language: python
sudo: required
dist: xenial
cache: pip
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - 'pypy3.5-6.0'

env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - MATRIX_TOXENV=unit

stages:
  - lint
  - test
  - integration

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=flake8
      stage: lint
    - python: 3.7
      env: TOXENV=pydocstyle
      stage: lint
    - python: 3.7
      env: TOXENV=apicheck
      stage: lint
    - python: 3.5
      env: MATRIX_TOXENV=integration-rabbitmq
      services:
        - docker
      stage: integration
    - python: 3.6
      env: MATRIX_TOXENV=integration-rabbitmq
      services:
        - docker
      stage: integration
    - python: 3.7
      env: MATRIX_TOXENV=integration-rabbitmq
      services:
        - docker
      stage: integration
    - python: pypy3.5-6.0
      env: MATRIX_TOXENV=integration-rabbitmq
      services:
        - docker
      stage: integration

before_install:
    - if [[ -v MATRIX_TOXENV ]]; then export TOXENV=${TRAVIS_PYTHON_VERSION}-${MATRIX_TOXENV}; fi; env
install:
  - pip --disable-pip-version-check install -U pip setuptools wheel | cat
  - pip --disable-pip-version-check install -U tox tox-docker | cat
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
notifications:
  irc:
    channels:
      - "chat.freenode.net#celery"
    on_success: change
    on_failure: change
